function result=equation(Zn1,Zn,func_f,A,d,tau,GP,GW)

Un1=Zn1(d+1:end,1);  Un=Zn(d+1:end,1);  new=Un1-Un;
F=GW(1)*func_f(Un+GP(1)*new) ... 
 +GW(2)*func_f(Un+GP(2)*new) ...
 +GW(3)*func_f(Un+GP(3)*new) ...
 +GW(4)*func_f(Un+GP(4)*new) ...
 +GW(5)*func_f(Un+GP(5)*new);  F=(-1)*F;

result=Zn1-Zn-0.5*tau*A*(Zn1+Zn)-tau*[F;zeros(d,1)];